# Site settings
title: Are we in space yet?
email: anowell@gmail.com
description: >
  This page tries to collect (pun intended) the state of rust in the aerospace industry.
  It tries to catalog the available crates and ongoing effort to run Rust in the air and in space.
baseurl: "" # the subpath of the site, e.g. /blog
url: "http://areweinspaceyet.org"

# Build settings
markdown: kramdown

exclude:
  - README.md
  - _tmp
  - Gemfile
  - LICENSE
  - vendor

collections:
  topics:
    output: true
    permalink: /:path/
